apiVersion: v1
kind: Service
metadata:
  name: flask-service
  namespace: mini-ci-cd

spec:
  type: NodePort
  selector:
    app: flask-app
  ports:
    - name: http
      port: 5000        # Port du Service (stable dans le cluster)
      targetPort: 5000  # Port exposé par le container dans le Pod
      nodePort:         # Port ouvert sur le nœud (valeur optionnel, sinon auto 30000-32767)
