name: CI/CD - Flask App

on:
  push:
    branches: [ "main" ]
    tags: ["v*"]

  pull_request:
    branches: [ "main" ]

jobs:
  test: # 1) Job CI: tests
    runs-on: ubuntu-latest
  
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with: 
          python-version: '3.10'

      - name: Install Dependencies
        run: |
            python -m pip install --upgrade pip
            pip install -r requirements.txt
      
      - name: Run Tests
        run: |
          pytest -v
  
  docker: # 2) Job CD: build & push image
    needs: test

    if: startsWith(github.ref, 'refs/tags/v')  # ne tourne QUE si on a poussé un tag 'v*'

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login Docker Hub
        uses: docker/login-action@v3
        with: 
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/mini-ci-cd-flask:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/mini-ci-cd-flask:${{ github.ref_name }}
